### PR TITLE
chore: delete example and add link to example

### PR DESCRIPTION
**Pull request by L2ncE**
#### What type of PR is this?

chore

#### What this PR does / why we need it (English/Chinese):

Move example into hertz-examples repository.

将 example 移动到 hertz-examples 库中。

#### Which issue(s) this PR fixes:

NA

### CODE REVIEW

**Comment by L2ncE** [comment]
@Duslia PLAT, thx~

**Comment by Duslia** [comment]
I think the example should be moved to hertz-examples repo?

**Comment by L2ncE** [comment]
> I think the example should be moved to hertz-examples repo?

Sounds good, please don't merge or close this PR for now, I will add the corresponding link in the README of this repo after the PR of hertz-example repo is merged.

**Comment by li-jin-gou** [comment]
Any progress?

**Comment by L2ncE** [comment]
> Any progress?

I see that PR has been merged, and I will change it immediately.

**Comment by L2ncE** [comment]
@li-jin-gou @Duslia Hello, have already finished.

**Comment by li-jin-gou** [comment]
LGTM

**Pull request merged**
